[project]
name = "arena-3-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.2",
    "ipykernel>=7.2.0",
    "ipynotebook>=0.1.0",
    "ipython>=9.14.0",
    "nbformat>=5.10.4",
    "numpy>=2.4.6",
    "pip>=26.1.1",
    "plotly>=6.7.0",
    "torch>=2.12.0",
]
